# Generated by Django 6.1.1 on 2026-09-24 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models

# PostGIS location column computed from lat/lng, plus a spatial (GiST) index —
# the same pattern as defects (see roadguard migration 0003).
ADD_LOCATION = """
    ALTER TABLE detections ADD COLUMN location geography(Point, 4326)
        GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography) STORED;
    CREATE INDEX detections_location_gist ON detections USING GIST (location);
"""
DROP_LOCATION = 'DROP INDEX IF EXISTS detections_location_gist; ALTER TABLE detections DROP COLUMN IF EXISTS location;'


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roadguard', '0003_mobile_reports_crowd_postgis'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.UUIDField(blank=True, null=True)),
                ('device_key', models.CharField(db_index=True, max_length=64)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('hazard_type', models.CharField(choices=[('Pothole', 'Pothole'), ('Crack', 'Crack')], default='Pothole', max_length=20)),
                ('confidence', models.FloatField()),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('model_version', models.CharField(max_length=60)),
                ('is_simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='telemetry.telemetrybatch')),
                ('defect', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detections', to='roadguard.defect')),
            ],
            options={
                'db_table': 'detections',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.RunSQL(ADD_LOCATION, reverse_sql=DROP_LOCATION),
    ]
