# Generated by Django 6.1.1 on 2026-09-24 16:41

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'travelers',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='travelers_email_unique_ci')],
            },
        ),
        migrations.CreateModel(
            name='TravelerSession',
            fields=[
                ('token_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mobile.traveler')),
            ],
            options={
                'db_table': 'traveler_sessions',
            },
        ),
    ]
