"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import importlib.util
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Secrets and DB credentials live in .env (see .env.example), not in code.
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ['DJANGO_SECRET_KEY']

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'False') == 'True'

# The host names this server answers to, from .env (comma-separated). The
# phone's ADB tunnel arrives as 127.0.0.1, so the default covers the app too.
# Never '*': that would accept requests for any host name.
ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'roadguard',   # web portal: defects, portal users, authorities, audit log
    'mobile',      # mobile app: traveller accounts, reports, hazards, places, routes
    'telemetry',   # sensor-data sharing: consent, batches, readings
    'detection',   # AI engine socket + grouping detections into spots
]

# True only behind the Docker setup's nginx, which sets X-Forwarded-For to
# the real client address (config/proxy.py). Never set it without a proxy
# in front: clients could then fake their address.
ROADGUARD_BEHIND_PROXY = os.environ.get('ROADGUARD_BEHIND_PROXY', 'False').strip().lower() in ('1', 'true', 'yes')

# WhiteNoise is installed only in the Docker image (Dockerfile), where
# gunicorn must serve the admin's static files itself. Without it (the
# .venv + runserver setup) nothing changes: runserver serves them.
_HAS_WHITENOISE = importlib.util.find_spec('whitenoise') is not None

MIDDLEWARE = [
    # First, so everything below sees the real client IP (config/proxy.py).
    'config.proxy.TrustedProxyMiddleware',
    # Serves the Django admin's CSS/JS in the Docker setup (see below).
    *(['whitenoise.middleware.WhiteNoiseMiddleware'] if _HAS_WHITENOISE else []),
    # Must sit above CommonMiddleware so CORS headers are added to every
    # response, including errors, for the React dev server.
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# External PostgreSQL server (the Windows postgresql-x64-17 service locally).
# Host/port/credentials all come from .env so pointing at a different server
# is a config change, not a code change.
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ['DB_NAME'],
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASSWORD'],
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}


# Django REST framework

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer',
                                 'rest_framework.renderers.BrowsableAPIRenderer'],
    # Every API request is identified by the portal session cookie
    # (roadguard/authentication.py); no other login method is accepted.
    'DEFAULT_AUTHENTICATION_CLASSES': ['roadguard.authentication.PortalSessionAuthentication'],
    # Locked by default: a view must opt out (like the login endpoints do)
    # to be reachable without logging in.
    'DEFAULT_PERMISSION_CLASSES': ['rest_framework.permissions.IsAuthenticated'],
    # Rate limit for the login / MFA / activation endpoints, per IP address,
    # to slow down password and code guessing (see auth_views.PublicAuthView).
    'DEFAULT_THROTTLE_RATES': {'auth': os.environ.get('AUTH_RATE_LIMIT', '10/minute')},
    # Identify callers by REMOTE_ADDR only. DRF's default reads the client-sent
    # X-Forwarded-For header, which let anyone dodge the limit by changing it.
    # Behind nginx, config/proxy.py has already put the real address there.
    'NUM_PROXIES': 0,
}

# Send the session cookie over HTTPS only. Turn on (.env
# DJANGO_SECURE_COOKIES=True) wherever the site is served over HTTPS;
# leave off for local http://localhost development.
SECURE_AUTH_COOKIES = os.environ.get('DJANGO_SECURE_COOKIES', 'False') == 'True'

# Base URL of the React frontend, used to build the activation link in
# invitation emails (e.g. http://localhost:5173/activate?token=...).
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173').rstrip('/')

# The one base path every backend URL lives under (config/urls.py), e.g.
# http://localhost:8000/api/v1/defects/. Always ends with "/", never starts with one.
API_PREFIX = os.environ.get('ROADGUARD_API_PREFIX', 'api/v1').strip('/') + '/'


def env_bool(name, default):
    """Read a True/False setting from .env."""
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes')


# --- Mobile app: external map services -------------------------------------
# Photon (place search + road names) and OSRM (driving routes). The defaults
# are free public servers without uptime guarantees; use your own for production.
ROADGUARD_PHOTON_URL = os.environ.get('ROADGUARD_PHOTON_URL', 'https://photon.komoot.io')
ROADGUARD_OSRM_URL = os.environ.get('ROADGUARD_OSRM_URL', 'https://router.project-osrm.org')
# Look up the road/region name for new defects from their coordinates.
ROADGUARD_REVERSE_GEOCODE = env_bool('ROADGUARD_REVERSE_GEOCODE', True)

# --- AI engine socket (detection/) ------------------------------------------
# In-process engine class (subclass of detection.engine.DetectionEngine).
ROADGUARD_AI_ENGINE = os.environ.get('ROADGUARD_AI_ENGINE', 'detection.engine.NullEngine')
# Run the in-process engine immediately after each upload (otherwise run
# `manage.py process_telemetry`, or let an external AI service claim batches).
ROADGUARD_AI_PROCESS_INLINE = env_bool('ROADGUARD_AI_PROCESS_INLINE', False)
# Key an external AI service sends as `Authorization: Api-Key <key>`.
# Empty = the /api/v1/ai/ endpoints are switched off.
ROADGUARD_AI_API_KEY = os.environ.get('ROADGUARD_AI_API_KEY', '')

# --- The sensor model in ai_engine/ (used when ROADGUARD_AI_ENGINE=ai_engine.sensor_model.PotholeEngine) ---
# The model file, and its SHA-256: the engine refuses to load a file that
# doesn't match (a pickle file can run code when loaded, so only the
# reviewed file is trusted). Update both together when the AI team ships a new model.
ROADGUARD_AI_MODEL_PATH = os.environ.get(
    'ROADGUARD_AI_MODEL_PATH', str(BASE_DIR / 'ai_engine' / 'models' / 'pothole_model_bundle.pkl'))
ROADGUARD_AI_MODEL_SHA256 = os.environ.get(
    'ROADGUARD_AI_MODEL_SHA256', '2c2e9ec7bdc05113b4058419bf398d207097eae0bb413f003460d00b1810d3bc')
# Which accelerometer readings the model reads: "acceleration" = raw, gravity
# included (what the training data contains), or "linear_acceleration" =
# gravity removed. To be confirmed with the AI team.
ROADGUARD_AI_ACCEL_KIND = os.environ.get('ROADGUARD_AI_ACCEL_KIND', 'acceleration')
# Turn each window so gravity points the way it did in training (phone upright
# in portrait). Helps when drivers hold or mount the phone differently.
ROADGUARD_AI_ALIGN_GRAVITY = env_bool('ROADGUARD_AI_ALIGN_GRAVITY', True)

# --- The photo model in ai_engine/ (YOLOv8, ai_engine/photo_model.py) -------
# Check each traveller's report photo for potholes once the report is
# submitted. The result is advice shown to officers; it changes nothing else.
ROADGUARD_PHOTO_CHECK = env_bool('ROADGUARD_PHOTO_CHECK', False)
# The model file and its SHA-256 (a .pt file is a pickle, so only the reviewed
# file is loaded). Update both together when the AI team ships a new model.
ROADGUARD_PHOTO_MODEL_PATH = os.environ.get(
    'ROADGUARD_PHOTO_MODEL_PATH', str(BASE_DIR / 'ai_engine' / 'models' / 'yolo-best.pt'))
ROADGUARD_PHOTO_MODEL_SHA256 = os.environ.get(
    'ROADGUARD_PHOTO_MODEL_SHA256', '01a4ad3e18deed8bdcf8b2564b0449755b2d52be675b45d764f33142a40d0fc4')
# Boxes less certain than this are ignored (0.25 is Ultralytics' default).
# PROVISIONAL: to be agreed with the AI team.
ROADGUARD_PHOTO_MIN_CONFIDENCE = float(os.environ.get('ROADGUARD_PHOTO_MIN_CONFIDENCE', 0.25))

# --- Crowd sensing: grouping detections into spots (detection/spots.py) -----
SPOT_RADIUS_M = float(os.environ.get('SPOT_RADIUS_M', 15))  # detections this close = same pothole
SPOT_MIN_CONFIDENCE = float(os.environ.get('SPOT_MIN_CONFIDENCE', 0.5))  # ignore less certain ones
SPOT_MIN_DEVICES_TO_TRACK = int(os.environ.get('SPOT_MIN_DEVICES_TO_TRACK', 2))  # → appears in the portal
SPOT_MIN_DEVICES_TO_PUBLISH = int(os.environ.get('SPOT_MIN_DEVICES_TO_PUBLISH', 3))  # → drivers are alerted
SPOT_STALE_DAYS = int(os.environ.get('SPOT_STALE_DAYS', 30))  # crowd-only spots expire without new hits
# Development only: also alert drivers about spots built from simulated detections.
ROADGUARD_PUBLISH_SIMULATED = env_bool('ROADGUARD_PUBLISH_SIMULATED', False)

# Mobile uploads: photos up to 15 MB are streamed to a temporary file.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 100

# React (Vite) dev server origins allowed to call the API with axios.
CORS_ALLOWED_ORIGINS = os.environ.get(
    'CORS_ALLOWED_ORIGINS', 'http://localhost:5173,http://127.0.0.1:5173'
).split(',')
# The axios client sends `withCredentials: true` (for session cookies);
# browsers reject such responses unless the server explicitly allows it.
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
# Where `collectstatic` gathers the Django admin's CSS/JS. Used by the Docker
# setup, where nginx serves them at /static/ (runserver serves them itself).
STATIC_ROOT = os.environ.get('DJANGO_STATIC_ROOT', str(BASE_DIR / 'staticfiles'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# No real mail server is configured yet, so outgoing emails (invitations)
# are stored in the outbox_emails table and shown at /api/v1/dev/outbox/ instead.
# To send real email, swap this for Django's SMTP backend, e.g.
#   'BACKEND': 'django.core.mail.backends.smtp.EmailBackend', plus host/port/user/password.
MAILERS = {
    'default': {
        'BACKEND': 'roadguard.email_backends.OutboxEmailBackend',
    },
}
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'RoadGuard AI <no-reply@roadguard.local>')
