# Generated by Django 6.1.1 on 2026-09-24 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('coverage_area', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'authorities',
                'db_table': 'authorities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('TARURA Officer', 'Tarura Officer')], max_length=20)),
                ('authority', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('last_active_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'portal_users',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('hazard_type', models.CharField(choices=[('Pothole', 'Pothole')], default='Pothole', max_length=20)),
                ('road', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('New', 'New'), ('Verified', 'Verified'), ('Under Repair', 'Under Repair'), ('Resolved', 'Resolved')], default='New', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('device', 'Device')], max_length=10)),
                ('confidence', models.FloatField(default=100.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('observation_count', models.PositiveIntegerField(default=1)),
                ('detected_at', models.DateTimeField()),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lng', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('has_photo', models.BooleanField(default=False)),
                ('review_note', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_defects', to='roadguard.portaluser')),
            ],
            options={
                'db_table': 'defects',
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['status'], name='defects_status_734a01_idx'), models.Index(fields=['region'], name='defects_region_db178d_idx')],
            },
        ),
    ]
