# Generated by Django 6.1.1 on 2026-09-24 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadguard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'outbox_emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='authority',
            options={'ordering': ['name'], 'verbose_name_plural': 'authorities'},
        ),
        migrations.AlterModelOptions(
            name='portaluser',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='portaluser',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='portaluser',
            name='password_hash',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='AdminSession',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('portal_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='roadguard.portaluser')),
            ],
            options={
                'db_table': 'admin_sessions',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=60)),
                ('resource_type', models.CharField(max_length=40)),
                ('resource_id', models.CharField(blank=True, max_length=40, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, db_column='actor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='roadguard.portaluser')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
