# Generated by Django 6.1.1 on 2026-09-24 16:41, then edited by hand for:
#   1. enabling PostGIS,
#   2. giving existing defects unique UUIDs safely (3 steps, see below),
#   3. the PostGIS `location` column + spatial index on defects.

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


def give_each_defect_a_uuid(apps, schema_editor):
    """Step 2 of adding the unique `uuid` field: a *different* UUID per existing row.

    (A plain AddField with default=uuid4 would give every existing row the same
    value and the unique constraint would fail.)
    """
    Defect = apps.get_model('roadguard', 'Defect')
    for defect in Defect.objects.filter(uuid__isnull=True).only('pk'):
        Defect.objects.filter(pk=defect.pk).update(uuid=uuid.uuid4())


# PostGIS location column, computed by PostgreSQL itself from lat/lng
# ("GENERATED ALWAYS ... STORED"), so it can never disagree with them.
# geography = coordinates on the Earth's surface; distances come out in metres.
# The GiST index makes "within X metres" and "inside this map area" fast.
ADD_LOCATION = """
    ALTER TABLE defects ADD COLUMN location geography(Point, 4326)
        GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography) STORED;
    CREATE INDEX defects_location_gist ON defects USING GIST (location);
"""
DROP_LOCATION = 'DROP INDEX IF EXISTS defects_location_gist; ALTER TABLE defects DROP COLUMN IF EXISTS location;'


class Migration(migrations.Migration):

    dependencies = [
        ('roadguard', '0002_auth_audit_outbox'),
    ]

    operations = [
        # Needs the PostGIS files installed on the PostgreSQL server. Creating
        # the extension needs a superuser the first time; if it already exists
        # (e.g. created by the setup steps in the README), this does nothing.
        migrations.RunSQL('CREATE EXTENSION IF NOT EXISTS postgis;', reverse_sql=migrations.RunSQL.noop),
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('content', models.BinaryField()),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'report_photos',
            },
        ),
        migrations.AddField(
            model_name='defect',
            name='client_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='defect',
            name='device_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='defect',
            name='gps_accuracy_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='gps_observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='defect',
            name='last_detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='defect',
            name='payload_digest',
            field=models.CharField(blank=True, default='', editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='defect',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='severity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='defect',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        # Unique `uuid`, in three steps: add it nullable, fill it per row, then
        # make it required and unique.
        migrations.AddField(
            model_name='defect',
            name='uuid',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(give_each_defect_a_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='defect',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='hazard_type',
            field=models.CharField(choices=[('Pothole', 'Pothole'), ('Crack', 'Crack')], default='Pothole', max_length=20),
        ),
        migrations.AddField(
            model_name='defect',
            name='photo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defect', to='roadguard.reportphoto'),
        ),
        migrations.RunSQL(ADD_LOCATION, reverse_sql=DROP_LOCATION),
    ]
