# Generated by Django 6.1.1 on 2026-09-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadguard', '0003_mobile_reports_crowd_postgis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='hazard_type',
            field=models.CharField(choices=[('Pothole', 'Pothole')], default='Pothole', max_length=20),
        ),
    ]
