# Generated by Django 6.1.1 on 2026-09-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadguard', '0004_potholes_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportphoto',
            name='ai_boxes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reportphoto',
            name='ai_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportphoto',
            name='ai_error',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reportphoto',
            name='ai_model_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reportphoto',
            name='ai_pothole_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
