# Generated by Django 6.1.1 on 2026-09-24 16:41

import django.db.models.deletion
import uuid
from django.db import migrations, models

# PostGIS location column computed from lat/lng, plus a spatial (GiST) index —
# the same pattern as defects (see roadguard migration 0003).
ADD_LOCATION = """
    ALTER TABLE sensor_readings ADD COLUMN location geography(Point, 4326)
        GENERATED ALWAYS AS (ST_SetSRID(ST_MakePoint(lng, lat), 4326)::geography) STORED;
    CREATE INDEX sensor_readings_location_gist ON sensor_readings USING GIST (location);
"""
DROP_LOCATION = 'DROP INDEX IF EXISTS sensor_readings_location_gist; ALTER TABLE sensor_readings DROP COLUMN IF EXISTS location;'


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mobile', '0001_initial'),
        # PostGIS is enabled by this roadguard migration; the location column below needs it.
        ('roadguard', '0003_mobile_reports_crowd_postgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_id', models.UUIDField()),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='mobile.traveler')),
            ],
            options={
                'db_table': 'collection_consents',
            },
        ),
        migrations.CreateModel(
            name='TelemetryBatch',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('trip_id', models.UUIDField()),
                ('payload_digest', models.CharField(max_length=64)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('ai_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('ai_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_processed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_model_version', models.CharField(blank=True, default='', max_length=60)),
                ('ai_error', models.CharField(blank=True, default='', max_length=500)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='telemetry.collectionconsent')),
            ],
            options={
                'db_table': 'telemetry_batches',
                'ordering': ['received_at'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=24)),
                ('recorded_at', models.DateTimeField(db_index=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('z', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('speed_mps', models.FloatField()),
                ('gps_accuracy_m', models.FloatField()),
                ('gps_observed_at', models.DateTimeField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='telemetry.telemetrybatch')),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['recorded_at', 'id'],
            },
        ),
        migrations.RunSQL(ADD_LOCATION, reverse_sql=DROP_LOCATION),
    ]
