"""Serializers: convert model objects to/from JSON and validate incoming data.

Each `fields` list is the exact JSON shape the frontend expects (see
frontend/src/lib/*.ts). Anything not listed, like password_hash and
mfa_secret, is never sent to the browser.
"""

from rest_framework import serializers

from .models import AuditLog, Authority, Defect, PortalUser, UserRole
from .security import MIN_PASSWORD_LENGTH


# ---------------------------------------------------------------------------
# Core records
# ---------------------------------------------------------------------------

class AuthoritySerializer(serializers.ModelSerializer):
    class Meta:
        model = Authority
        fields = ['id', 'name', 'coverage_area', 'contact', 'status']
        read_only_fields = ['id']  # ids are generated by the server


class PortalUserSerializer(serializers.ModelSerializer):
    """A portal user as listed on the Users page, and edited by an Admin."""

    class Meta:
        model = PortalUser
        fields = ['id', 'name', 'email', 'phone', 'role', 'authority', 'status',
                  'last_active_at', 'created_at']
        read_only_fields = ['id', 'last_active_at', 'created_at']


class InviteUserSerializer(serializers.ModelSerializer):
    """Input for POST /api/v1/users/invite/.

    Only the details an Admin fills in on the Add User form. There's no
    password or status field: the account starts Inactive and the invitee
    chooses their own password from the activation email.
    """

    class Meta:
        model = PortalUser
        fields = ['name', 'email', 'phone', 'role', 'authority']
        # The model's unique=True on email already rejects a duplicate here,
        # with the message below instead of Django's generic one.
        extra_kwargs = {'email': {'error_messages': {
            'unique': 'An account with this email already exists'}}}


class DefectSerializer(serializers.ModelSerializer):
    """A defect as shown on the Dashboard, Map and Reports pages."""

    # The frontend shows the reviewer's *name* ("Last reviewed by Jane Doe"),
    # so the name is sent instead of the USR-... id stored in the column.
    reviewed_by = serializers.CharField(source='reviewed_by.name', read_only=True,
                                        default=None)
    # True only when a photo is really stored, so the portal never offers a
    # photo that GET /api/v1/defects/<id>/photo/ can't return (sample defects
    # carry the has_photo flag without any image).
    has_photo = serializers.SerializerMethodField()
    # Whether the mobile app currently shows/alerts this defect to drivers,
    # decided by the same rule as the app's live map (mobile/hazards.py).
    shown_to_drivers = serializers.SerializerMethodField()

    def get_has_photo(self, defect):
        return defect.photo_id is not None

    def get_shown_to_drivers(self, defect):
        from mobile.hazards import is_visible_to_drivers  # local import: avoids an import cycle
        return is_visible_to_drivers(defect)

    class Meta:
        model = Defect
        fields = ['id', 'hazard_type', 'road', 'region', 'severity', 'status', 'source',
                  'confidence', 'observation_count', 'detected_at', 'lat', 'lng',
                  'has_photo', 'review_note', 'reviewed_by', 'reviewed_at',
                  # Mobile report note, and the crowd-sensing numbers kept up to
                  # date by detection/spots.py (see Defect model comments).
                  'notes', 'device_count', 'severity_score', 'last_detected_at',
                  'published_at', 'is_simulated', 'shown_to_drivers']
        # reviewed_by / reviewed_at are stamped by the server from the logged-in
        # user (DefectDetailView), so a client can't claim someone else reviewed
        # it. The crowd numbers are computed from detections, never typed in.
        read_only_fields = ['id', 'reviewed_at', 'notes', 'device_count', 'severity_score',
                            'last_detected_at', 'published_at', 'is_simulated']


class AuditLogSerializer(serializers.ModelSerializer):
    class Meta:
        model = AuditLog
        fields = ['id', 'actor_email', 'action', 'resource_type', 'resource_id',
                  'details', 'ip_address', 'created_at']
        read_only_fields = fields  # the audit log can only be read, never edited


# ---------------------------------------------------------------------------
# Auth request/response bodies (not tied to one model, hence plain Serializers)
# ---------------------------------------------------------------------------

class LoginSerializer(serializers.Serializer):
    """Body of POST /api/v1/auth/login/ — step 1, email + password."""
    email = serializers.CharField()
    password = serializers.CharField(trim_whitespace=False)


class VerifyMfaSerializer(serializers.Serializer):
    """Body of POST /api/v1/auth/verify-mfa/ — step 2, the authenticator code."""
    pending_token = serializers.CharField()
    code = serializers.CharField(max_length=10)


class AcceptInviteSerializer(serializers.Serializer):
    """Body of POST /api/v1/auth/accept-invite/ — the invitee sets their password."""
    token = serializers.CharField()
    password = serializers.CharField(min_length=MIN_PASSWORD_LENGTH, trim_whitespace=False,
                                     error_messages={'min_length':
                                                     f'Use at least {MIN_PASSWORD_LENGTH} characters'})


class CurrentUserSerializer(serializers.ModelSerializer):
    """The logged-in user, as returned by /auth/verify-mfa/ and /auth/me/.

    Same shape as the frontend's AuthUser, plus `id`.
    """
    role = serializers.ChoiceField(choices=UserRole.choices)

    class Meta:
        model = PortalUser
        fields = ['id', 'name', 'email', 'role']
